name: Create EKS Cluster

on:
  workflow_dispatch:

jobs:

  create-cluster:
    name: Create EKS Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Create EKS Cluster
      run: |
        eksctl create cluster -f config-files/cluster-setup.yaml
        sleep 60


  setup-ebs-csi-driver:
    name: Set up EBS CSI Driver
    needs: create-cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name zCluster --region eu-central-1

    - name: Install EBS CSI Driver
      run: |
        eksctl utils associate-iam-oidc-provider --cluster zCluster --region eu-central-1 --approve
        eksctl create iamserviceaccount --name ebs-csi-controller-sa --namespace kube-system  --cluster zCluster --role-name AmazonEKS_EBS_CSI_DriverRole --role-only --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy --approve
        eksctl create addon --name aws-ebs-csi-driver --cluster zCluster --region eu-central-1 --service-account-role-arn arn:aws:iam::845465762943:role/AmazonEKS_EBS_CSI_DriverRole